import z from 'zod';

export const pathfinderDataSchema = z.object({
  nome: z.string({ required_error: 'Campo obrigatório' }),
  dataNascimento: z.string(), //z.coerce.date({ required_error: 'Campo obrigatório' }),
  sexo: z.string({ required_error: 'Campo obrigatório' }),
  estadoCivil: z.string().min(1, { message: 'Campo obrigatório' }),
  rg: z.string(),
  orgaoExpedidor: z.string(),
  cpf: z.string(),
  certidaoNascimento: z.string(),
  email: z.string(),
  telefone: z.string(),
  celular: z.string(),
  possuiWhatsapp: z.boolean(),
  cep: z.string(),
  endereco: z.string(),
  bairro: z.string(),
  numero: z.string(),
  complemento: z.string(),
  cidade: z.string(),
  uf: z.string(),
  nomeMae: z.string(),
  cpfMae: z.string(),
  celularMae: z.string(),
  possuiWhatsappMae: z.boolean(),
  nomePai: z.string(),
  cpfPai: z.string(),
  celularPai: z.string(),
  possuiWhatsappPai: z.boolean(),
  tamanhoCamiseta: z.string(),
  igreja: z.string(),
  ehAdventistaBatizado: z.boolean(),
  nomeResponsavel: z.string(),
  cpfResponsavel: z.string(),
  grauParentescoResponsavel: z.string(),
  emailResposavel: z.string(),
  celularResponsavel: z.string(),
  contatoEmergencia: z.string(),
  grauParentescoEmergencia: z.string(),
  foneEmergencia: z.string(),
  planoSaude: z.string(),
  numeroPlanoSaude: z.string(),
  numeroSus: z.string(),
  dataVacinaTetano: z.string(),
  altura: z.string(),
  peso: z.string(),
  tipoSanguineo: z.string(),
  sabeNadar: z.boolean(),
  possuiEnfermidade: z.boolean(),
  tomaRemedio: z.boolean(),
  temAlergiaRemedio: z.boolean(),
  temOutraAlergia: z.boolean(),
  temProblemasPsicologicos: z.boolean(),
  teveFraturaRecente: z.boolean(),
  temRestricaoAlimentar: z.boolean(),
  temProblemasCardiacos: z.boolean(),
  ehDiabetico: z.boolean(),
  temProblemasRenais: z.boolean(),
  teveProblemasDeSaudeRecentes: z.boolean(),
  fezTransfusaoDeSangue: z.boolean(),
  medicamentosUsadosRecentemente: z.string(),
  observacoes: z.string(),
  teveCatapora: z.boolean(),
  teveRubeola: z.boolean(),
  teveFebreAmarela: z.boolean(),
  teveTetano: z.boolean(),
  teveCaxumba: z.boolean(),
  teveMenigite: z.boolean(),
  teveBronquite: z.boolean(),
  teveH1n1: z.boolean(),
  teveVariola: z.boolean(),
  teveCovid: z.boolean(),
  tevePneumonia: z.boolean(),
  teveDengue: z.boolean(),
  teveSarampo: z.boolean(),
  teveCoqueluche: z.boolean(),
  teveRinite: z.boolean(),
  teveColera: z.boolean(),
  teveMalaria: z.boolean(),
  teveHepatite: z.boolean(),
  teveDifteria: z.boolean(),
  ehDeficienteAuditivo: z.boolean(),
  ehDeficienteVisual: z.boolean(),
  ehDeficienteFisico: z.boolean(),
  termosDeUso: z.boolean(),
});
